teacher_train:
  model_name: teacherNet
  task_name: base
  save_dir: ./log
  seed: 42
  max_epochs: 500
  valid_frequency: 1
  ckpt_name: last

optim:
  lr_init: 2e-4
  lr_min: 1e-6
  warmup_epochs: 5
  weight_decay: 1e-8



distill_train:
  model_name: distillNet
  task_name: base
  save_dir: ./log
  seed: 42
  max_epochs: 500
  valid_frequency: 1
  ckpt_name: last


data:
  train_path: E:/Dataset/train
  train_batch_size: 1
  train_img_size: 256
  valid_path: E:/Dataset/test
  valid_batch_size: 1
  valid_img_size: 256
  num_workers: 1
  pin_memory: True

